In [3]:
import numpy as np
a=[1,2,3,4,5]
myarr=np.array(a)
myarr

array([1, 2, 3, 4, 5])

In [5]:
import numpy as np
a=[]
n=int(input("enter the size of array"))
for i in range(n):
    val=int(input("enter number"))
    a.append(val)
myarr=np.array(a)
myarr

enter the size of array5
enter number1
enter number2
enter number3
enter number4
enter number5


array([1, 2, 3, 4, 5])

In [6]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
myarr=np.array(a)
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
myarr=np.array(a)
myarr
print("total dimension=",myarr.ndim)
print("shape of array=",myarr.shape)

total dimension= 2
shape of array= (3, 3)


In [8]:
import numpy as np
a=[5]
arr=np.zeros(a)
arr

array([0., 0., 0., 0., 0.])

In [10]:
import numpy as np
a=[2,3]
arr=np.zeros(a)
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
import numpy as np
arr=np.eye(5,8)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [17]:
import numpy as np
arr=np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [25]:
import numpy as np
a=[]
size=int(input("how many numbers"))
for i in range(size):
    val=int(input("enter number"))
    a.append(val)
    arr=np.array(a)
    for i in range(arr.size):
        print(arr[i])

how many numbers3
enter number54
54
enter number55
54
55
enter number57
54
55
57


In [28]:
import numpy as np
a=[]
size=int(input("how many numbers"))
for i in range(size):
    val=int(input("enter number"))
    a.append(val)
    arr=np.array(a)
    for i in range(arr.size):
        print(arr[i])
sum=0        
sum=sum+arr[i]
print("sum of array=",sum)

how many numbers5
enter number1
1
enter number2
1
2
enter number3
1
2
3
enter number4
1
2
3
4
enter number5
1
2
3
4
5
sum of array= 5


In [33]:
import numpy as np
a=[]
size=int(input("how many numbers"))
for i in range(size):
    val=int(input("enter the number"))
    a.append(val)
    arr=np.array(a)
    for i in range(arr.size):
        print(arr[i])
sum=0
for i in range(arr.size):
    sum=sum+arr[i]
    print("sum of array=",sum)

how many numbers4
enter the number1
1
enter the number2
1
2
enter the number3
1
2
3
enter the number4
1
2
3
4
sum of array= 1
sum of array= 3
sum of array= 6
sum of array= 10


In [39]:
import numpy as np
a=[]
size=int(input("how many numbers"))
for i in range(size):
    val=int(input("enter number"))
    a.append(val)
    arr=np.array(a)
    for i in range(arr.size):
        print(arr[i])
        sum=0
        for i in range(arr.size):
            sum=sum+arr[i]
            print(arr[i])
            arr1=arr[2:5]
            print(arr1)

how many numbers8
enter number1
1
1
[]
enter number2
1
1
[]
2
[]
2
1
[]
2
[]
enter number3
1
1
[3]
2
[3]
3
[3]
2
1
[3]
2
[3]
3
[3]
3
1
[3]
2
[3]
3
[3]
enter number4
1
1
[3 4]
2
[3 4]
3
[3 4]
4
[3 4]
2
1
[3 4]
2
[3 4]
3
[3 4]
4
[3 4]
3
1
[3 4]
2
[3 4]
3
[3 4]
4
[3 4]
4
1
[3 4]
2
[3 4]
3
[3 4]
4
[3 4]
enter number5
1
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
2
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
3
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
4
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
5
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
enter number6
1
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
6
[3 4 5]
2
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
6
[3 4 5]
3
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
6
[3 4 5]
4
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
6
[3 4 5]
5
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
6
[3 4 5]
6
1
[3 4 5]
2
[3 4 5]
3
[3 4 5]
4
[3 4 5]
5
[3 4 5]
6
[3 4 5]
enter number7
1
1
[3 4 5]
2
[3 4 5]
3
[

In [6]:
import numpy as np
a=[]
n=int(input("enter the sizze of array"))
for i in range(n):
    val=int(input("enter number"))
    a.append(val)
arr=np.array(a)
arr

enter the sizze of array4
enter number1
enter number2
enter number3
enter number4


array([1, 2, 3, 4])

In [7]:
import numpy as np
a=[]
n=int(input("enter the size of array"))
for i in range(n):
    val=int(input("enter number"))
    a.append(val)
myarr=np.array(a)
myarr

enter the size of array3
enter number12
enter number2
enter number3


array([12,  2,  3])

In [10]:
a=15
b=20
if a>b:
    print("bigger")
else:
    print("smaller")

smaller


In [13]:
a=int(input("enter the number"))
b=int(input("enter 2nd number"))
if a>b:
    print("bigger")
else:
    print("smaller")

enter the number10
enter 2nd number5
bigger


In [1]:
import numpy as np
arr=np.random.randint(1,50,12)
arr

array([43, 36,  8,  8, 35, 23, 12, 11, 28, 24, 11, 37])

In [6]:
import numpy as np
arr=np.random.randint(1,100,12)
arr=arr.reshape(3,4)
arr

array([[58, 37, 49, 54],
       [70, 47, 66,  9],
       [ 3, 60, 86, 59]])